/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CompetitorData = IDL.Record({
  'url' : IDL.Text,
  'metaDescription' : IDL.Text,
  'title' : IDL.Text,
  'contentLength' : IDL.Nat,
  'keywordDensity' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CrawlRequest = IDL.Record({
  'url' : IDL.Text,
  'followInternalLinks' : IDL.Bool,
  'depth' : IDL.Nat,
});
export const PageAudit = IDL.Record({
  'url' : IDL.Text,
  'metaDescription' : IDL.Text,
  'title' : IDL.Text,
  'imageAltTexts' : IDL.Vec(IDL.Text),
  'slug' : IDL.Text,
  'h2Headings' : IDL.Vec(IDL.Text),
  'issues' : IDL.Vec(IDL.Text),
  'h1Headings' : IDL.Vec(IDL.Text),
  'canonicalUrl' : IDL.Text,
});
export const CrawlSession = IDL.Record({
  'id' : IDL.Text,
  'rootUrl' : IDL.Text,
  'timestamp' : IDL.Int,
  'pages' : IDL.Vec(PageAudit),
});
export const SeoRecommendation = IDL.Record({
  'id' : IDL.Text,
  'recommendedMetaDescription' : IDL.Text,
  'recommendedSlug' : IDL.Text,
  'competitorAnalysis' : IDL.Vec(CompetitorData),
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'recommendedTitle' : IDL.Text,
  'targetKeyword' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'analyzeCompetitors' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(CompetitorData)],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'crawlWebsite' : IDL.Func([CrawlRequest], [CrawlSession], []),
  'generateSeoRecommendation' : IDL.Func(
      [IDL.Text, IDL.Text],
      [SeoRecommendation],
      [],
    ),
  'getAllCrawlSessions' : IDL.Func([], [IDL.Vec(CrawlSession)], ['query']),
  'getAllRecommendations' : IDL.Func(
      [],
      [IDL.Vec(SeoRecommendation)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCrawlSessionById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CrawlSession)],
      ['query'],
    ),
  'getRecommendationByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SeoRecommendation)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CompetitorData = IDL.Record({
    'url' : IDL.Text,
    'metaDescription' : IDL.Text,
    'title' : IDL.Text,
    'contentLength' : IDL.Nat,
    'keywordDensity' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CrawlRequest = IDL.Record({
    'url' : IDL.Text,
    'followInternalLinks' : IDL.Bool,
    'depth' : IDL.Nat,
  });
  const PageAudit = IDL.Record({
    'url' : IDL.Text,
    'metaDescription' : IDL.Text,
    'title' : IDL.Text,
    'imageAltTexts' : IDL.Vec(IDL.Text),
    'slug' : IDL.Text,
    'h2Headings' : IDL.Vec(IDL.Text),
    'issues' : IDL.Vec(IDL.Text),
    'h1Headings' : IDL.Vec(IDL.Text),
    'canonicalUrl' : IDL.Text,
  });
  const CrawlSession = IDL.Record({
    'id' : IDL.Text,
    'rootUrl' : IDL.Text,
    'timestamp' : IDL.Int,
    'pages' : IDL.Vec(PageAudit),
  });
  const SeoRecommendation = IDL.Record({
    'id' : IDL.Text,
    'recommendedMetaDescription' : IDL.Text,
    'recommendedSlug' : IDL.Text,
    'competitorAnalysis' : IDL.Vec(CompetitorData),
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'recommendedTitle' : IDL.Text,
    'targetKeyword' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'analyzeCompetitors' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(CompetitorData)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'crawlWebsite' : IDL.Func([CrawlRequest], [CrawlSession], []),
    'generateSeoRecommendation' : IDL.Func(
        [IDL.Text, IDL.Text],
        [SeoRecommendation],
        [],
      ),
    'getAllCrawlSessions' : IDL.Func([], [IDL.Vec(CrawlSession)], ['query']),
    'getAllRecommendations' : IDL.Func(
        [],
        [IDL.Vec(SeoRecommendation)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCrawlSessionById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CrawlSession)],
        ['query'],
      ),
    'getRecommendationByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SeoRecommendation)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };