/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompetitorData {
  'url' : string,
  'metaDescription' : string,
  'title' : string,
  'contentLength' : bigint,
  'keywordDensity' : bigint,
}
export interface CrawlRequest {
  'url' : string,
  'followInternalLinks' : boolean,
  'depth' : bigint,
}
export interface CrawlSession {
  'id' : string,
  'rootUrl' : string,
  'timestamp' : bigint,
  'pages' : Array<PageAudit>,
}
export interface PageAudit {
  'url' : string,
  'metaDescription' : string,
  'title' : string,
  'imageAltTexts' : Array<string>,
  'slug' : string,
  'h2Headings' : Array<string>,
  'issues' : Array<string>,
  'h1Headings' : Array<string>,
  'canonicalUrl' : string,
}
export interface SeoRecommendation {
  'id' : string,
  'recommendedMetaDescription' : string,
  'recommendedSlug' : string,
  'competitorAnalysis' : Array<CompetitorData>,
  'timestamp' : bigint,
  'category' : string,
  'recommendedTitle' : string,
  'targetKeyword' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'analyzeCompetitors' : ActorMethod<[string, string], Array<CompetitorData>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'crawlWebsite' : ActorMethod<[CrawlRequest], CrawlSession>,
  'generateSeoRecommendation' : ActorMethod<
    [string, string],
    SeoRecommendation
  >,
  'getAllCrawlSessions' : ActorMethod<[], Array<CrawlSession>>,
  'getAllRecommendations' : ActorMethod<[], Array<SeoRecommendation>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCrawlSessionById' : ActorMethod<[string], [] | [CrawlSession]>,
  'getRecommendationByCategory' : ActorMethod<
    [string],
    [] | [SeoRecommendation]
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];